version: '3.4'

services:
  portfolio:
    container_name: portfolio_api
    hostname: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: "Vh267g2MFXvlJIwfrUYch"
      POSTGRES_USER: "app"
      POSTGRES_DB: "application"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes: 
     pgdata: